### ISSUE TITLE
开启录像功能，然后结束录像。重复几次应用闪退。

### ISSUE THREAD

**Issue by fhfgy** [moo611/opencamera-for-android#17]
开启录像功能，然后结束录像。重复几次应用闪退。

**Comment by fhfgy** [comment]
解决了，闪退的原因是内存泄露。
停止录像时，由于线程的执行原因mEglCore并没有释放掉。

**Comment by moo611** [comment]
我这里也出现了闪退，但是是创建文件时没适配android Q的原因，我也修复一下。

**Comment by moo611** [comment]
已重构
